class ValidationSignUpState{}
class ValidationSignUpInitialState extends ValidationSignUpState{}

class ValidateUserNameTrueSigUpState extends ValidationSignUpState {}
class ValidateUserNameFalseSigUpState extends ValidationSignUpState {}

class ValidatePasswordTrueSigUpState extends ValidationSignUpState {}
class ValidatePasswordFalseSigUpState extends ValidationSignUpState {}

class ValidateConfirmPasswordTrueSigUpState extends ValidationSignUpState {}
class ValidateConfirmPasswordFalseSigUpState extends ValidationSignUpState {}

class TogglePasswordVisibilitySignUpState extends ValidationSignUpState {}
class ToggleConfirmPasswordVisibilitySignUpState extends ValidationSignUpState {}