// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLT2Br1D2T72i-0B2MKOLLuq-qIiIy8vk',
    appId: '1:1094498208734:web:128a7b3833e75b09b02b4f',
    messagingSenderId: '1094498208734',
    projectId: 'newsappcode',
    authDomain: 'newsappcode.firebaseapp.com',
    storageBucket: 'newsappcode.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIg66MR56ShitlazYG1_HRogUF1WNxbcw',
    appId: '1:1094498208734:android:e89ac851db88847eb02b4f',
    messagingSenderId: '1094498208734',
    projectId: 'newsappcode',
    storageBucket: 'newsappcode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVurwmfMGfy1yjJ6H5m33Raz3Kcu31YK0',
    appId: '1:1094498208734:ios:633d6d6ddb7caba9b02b4f',
    messagingSenderId: '1094498208734',
    projectId: 'newsappcode',
    storageBucket: 'newsappcode.appspot.com',
    iosBundleId: 'com.example.newsappcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVurwmfMGfy1yjJ6H5m33Raz3Kcu31YK0',
    appId: '1:1094498208734:ios:633d6d6ddb7caba9b02b4f',
    messagingSenderId: '1094498208734',
    projectId: 'newsappcode',
    storageBucket: 'newsappcode.appspot.com',
    iosBundleId: 'com.example.newsappcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLT2Br1D2T72i-0B2MKOLLuq-qIiIy8vk',
    appId: '1:1094498208734:web:1af9d5338782cd6eb02b4f',
    messagingSenderId: '1094498208734',
    projectId: 'newsappcode',
    authDomain: 'newsappcode.firebaseapp.com',
    storageBucket: 'newsappcode.appspot.com',
  );
}
